### ISSUE TITLE
Add quiet option

### ISSUE THREAD

**Issue by edwardloveall** [infrablocks/ruby_gpg2#73]
Hello, and thanks for the library.

I'm wondering if you'd be open to adding the ability to pass the `--quiet` flag. Right now, running commands like `--import` print informational text which is not ideal; especially in tests. The ability to pass `--quiet` would clean that up.

**Comment by tobyclemson** [comment]
Hi @edwardloveall,

We'd happily accept a PR for this.

Thanks,
Toby

**Comment by edwardloveall** [comment]
Fair enough! May not get to this for a few weeks.

**Comment by Gryff** [comment]
@edwardloveall this is available to test in [v0.13.0.pre.4](https://github.com/infrablocks/ruby_gpg2/releases/tag/v0.13.0.pre.4)

**Comment by edwardloveall** [comment]
Works great, thank you!
